/* Generated By:JavaCC: Do not edit this line. langXConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int INT = 2;
  /** RegularExpression Id. */
  int STRING = 3;
  /** RegularExpression Id. */
  int IDENT = 4;
  /** RegularExpression Id. */
  int RBRACKET = 5;
  /** RegularExpression Id. */
  int LBRACKET = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int EXTENDS = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"int\"",
    "\"string\"",
    "\"ident\"",
    "\"}\"",
    "\"{\"",
    "\",\"",
    "\")\"",
    "\"(\"",
    "\"CONSTRUCTOR\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"extends\"",
  };

}
