/* Generated By:JavaCC: Do not edit this line. TokenizerTokenManager.java */
package br.univali.comp.parser.tokenizer;

/** Token Manager. */
public class TokenizerTokenManager implements TokenizerConstants
{
        static int commentLevel = 0 ;

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 2);
      case 32:
         return jjStopAtPos(0, 1);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x4L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x10000000000L, 0x0L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0x10000000000000L, 0x0L
};
static final long[] jjbitVec3 = {
   0x0L, 0x0L, 0x1000000000000L, 0x0L
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0x40000000000L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 329;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0xac2000000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if ((0x530000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  else if ((0x5000004200000000L & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                  }
                  else if ((0x8000009800000000L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 58)
                     jjAddStates(3, 4);
                  else if (curChar == 61)
                     jjCheckNAdd(58);
                  if (curChar == 62)
                     jjCheckNAdd(58);
                  else if (curChar == 60)
                     jjCheckNAdd(58);
                  else if (curChar == 33)
                     jjCheckNAdd(58);
                  else if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 4;
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0xac2000000000L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 4:
                  if (curChar == 42 && kind > 8)
                     kind = 8;
                  break;
               case 5:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 37 && kind > 8)
                     kind = 8;
                  break;
               case 7:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 57:
                  if ((0x5000004200000000L & l) != 0L && kind > 11)
                     kind = 11;
                  break;
               case 58:
                  if (curChar == 61 && kind > 11)
                     kind = 11;
                  break;
               case 59:
                  if (curChar == 61)
                     jjCheckNAdd(58);
                  break;
               case 60:
                  if (curChar == 33)
                     jjCheckNAdd(58);
                  break;
               case 61:
                  if (curChar == 60)
                     jjCheckNAdd(58);
                  break;
               case 62:
                  if (curChar == 62)
                     jjCheckNAdd(58);
                  break;
               case 63:
                  if ((0x530000000000L & l) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 64:
                  if ((0x8000009800000000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(5, 7);
                  break;
               case 102:
                  if (curChar == 58)
                     jjAddStates(3, 4);
                  break;
               case 103:
                  if (curChar != 45)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(8, 35);
                  break;
               case 105:
                  if ((0xd000fffb00000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 106:
                  if (curChar != 37)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 107:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar != 42)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 109:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 158:
                  if (curChar != 61)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 159:
                  if (curChar == 62)
                     jjCheckNAdd(158);
                  break;
               case 160:
                  if (curChar == 60)
                     jjCheckNAdd(158);
                  break;
               case 161:
                  if (curChar == 33)
                     jjCheckNAdd(158);
                  break;
               case 162:
                  if (curChar == 61)
                     jjCheckNAdd(158);
                  break;
               case 163:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 164:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(64, 93);
                  break;
               case 165:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 166:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(94, 121);
                  break;
               case 178:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(122, 124);
                  break;
               case 204:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(125, 155);
                  break;
               case 205:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(156, 159);
                  break;
               case 206:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(165);
                  break;
               case 207:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(206, 165);
                  break;
               case 208:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(160, 162);
                  break;
               case 209:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(163, 194);
                  break;
               case 210:
                  if (curChar == 42)
                     jjCheckNAddStates(195, 222);
                  break;
               case 212:
                  if ((0xd000fffb00002600L & l) != 0L)
                     jjCheckNAddStates(223, 250);
                  break;
               case 213:
                  if (curChar == 37)
                     jjCheckNAddStates(223, 250);
                  break;
               case 214:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 263:
                  if (curChar == 61)
                     jjCheckNAddStates(223, 250);
                  break;
               case 264:
                  if (curChar == 62)
                     jjCheckNAdd(263);
                  break;
               case 265:
                  if (curChar == 60)
                     jjCheckNAdd(263);
                  break;
               case 266:
                  if (curChar == 33)
                     jjCheckNAdd(263);
                  break;
               case 267:
                  if (curChar == 61)
                     jjCheckNAdd(263);
                  break;
               case 268:
                  if (curChar == 10)
                     jjCheckNAddStates(223, 250);
                  break;
               case 269:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(251, 280);
                  break;
               case 271:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 272:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(281, 308);
                  break;
               case 273:
                  if (curChar == 42)
                     jjAddStates(309, 310);
                  break;
               case 274:
                  if (curChar == 42)
                     jjCheckNAddStates(223, 250);
                  break;
               case 277:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(311, 313);
                  break;
               case 312:
                  if (curChar == 58 && kind > 5)
                     kind = 5;
                  break;
               case 313:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(314, 344);
                  break;
               case 314:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(345, 348);
                  break;
               case 315:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(271);
                  break;
               case 316:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(315, 271);
                  break;
               case 317:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(349, 351);
                  break;
               case 318:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(352, 383);
                  break;
               case 319:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddStates(0, 2);
                  break;
               case 320:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 321:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 322:
                  if ((0x3ff000000000000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 323:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(384, 387);
                  break;
               case 324:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(320);
                  break;
               case 325:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(324, 320);
                  break;
               case 326:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(388, 390);
                  break;
               case 327:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 328;
                  break;
               case 328:
                  if ((0x3ff000000000000L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  else if ((0x2800000028000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  else if (curChar == 96)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 124)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(391, 396);
                  else if (curChar == 95)
                     jjCheckNAddStates(397, 400);
                  if (curChar == 116)
                     jjCheckNAddTwoStates(91, 101);
                  else if (curChar == 110)
                     jjAddStates(401, 402);
                  else if (curChar == 100)
                     jjCheckNAddTwoStates(90, 91);
                  else if (curChar == 112)
                     jjAddStates(403, 404);
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 54;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 47;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 43;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 39;
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 8:
                  if (curChar == 101 && kind > 9)
                     kind = 9;
                  break;
               case 9:
               case 33:
                  if (curChar == 108)
                     jjCheckNAdd(8);
                  break;
               case 10:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 115 && kind > 9)
                     kind = 9;
                  break;
               case 17:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 116)
                     jjCheckNAdd(8);
                  break;
               case 19:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 116 && kind > 9)
                     kind = 9;
                  break;
               case 25:
               case 27:
                  if (curChar == 101)
                     jjCheckNAdd(24);
                  break;
               case 26:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 28:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 112 && kind > 9)
                     kind = 9;
                  break;
               case 30:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 34:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 115)
                     jjCheckNAdd(8);
                  break;
               case 38:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 108 && kind > 9)
                     kind = 9;
                  break;
               case 42:
               case 94:
                  if (curChar == 97)
                     jjCheckNAdd(41);
                  break;
               case 43:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 114 && kind > 9)
                     kind = 9;
                  break;
               case 46:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 110 && kind > 9)
                     kind = 9;
                  break;
               case 50:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x7fffffe87fffffeL & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 57:
                  if (curChar == 124 && kind > 11)
                     kind = 11;
                  break;
               case 63:
                  if ((0x2800000028000000L & l) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 64:
                  if (curChar == 96 && kind > 13)
                     kind = 13;
                  break;
               case 70:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(391, 396);
                  break;
               case 71:
                  if (curChar == 95)
                     jjCheckNAdd(72);
                  break;
               case 73:
                  if (curChar == 95)
                     jjCheckNAddStates(397, 400);
                  break;
               case 74:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(72);
                  break;
               case 75:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 76:
                  if ((0x7fffffe07fffffeL & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 77:
                  if (curChar == 95 && kind > 10)
                     kind = 10;
                  break;
               case 78:
                  if (curChar == 112)
                     jjAddStates(403, 404);
                  break;
               case 79:
                  if (curChar == 109 && kind > 9)
                     kind = 9;
                  break;
               case 80:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 117)
                     jjCheckNAdd(24);
                  break;
               case 86:
                  if (curChar == 100)
                     jjCheckNAddTwoStates(90, 91);
                  break;
               case 87:
                  if (curChar == 110)
                     jjCheckNAdd(8);
                  break;
               case 88:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 111 && kind > 9)
                     kind = 9;
                  break;
               case 92:
                  if (curChar == 110)
                     jjAddStates(401, 402);
                  break;
               case 93:
                  if (curChar == 111)
                     jjCheckNAdd(24);
                  break;
               case 95:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(91, 101);
                  break;
               case 100:
                  if (curChar == 117)
                     jjCheckNAdd(8);
                  break;
               case 101:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 104:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 105:
                  if ((0x3800000128000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 110:
                  if (curChar != 110)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 111:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar != 114)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 118:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar != 108)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 122:
               case 168:
                  if (curChar == 97)
                     jjCheckNAdd(121);
                  break;
               case 123:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar != 101)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 126:
                  if (curChar == 115)
                     jjCheckNAdd(125);
                  break;
               case 127:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
               case 151:
                  if (curChar == 108)
                     jjCheckNAdd(125);
                  break;
               case 131:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar != 112)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 135:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar != 116)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 139:
               case 141:
                  if (curChar == 101)
                     jjCheckNAdd(138);
                  break;
               case 140:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 142:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 116)
                     jjCheckNAdd(125);
                  break;
               case 144:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar != 115)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 150:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 152:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 167:
                  if (curChar == 110)
                     jjAddStates(405, 406);
                  break;
               case 169:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 111)
                     jjCheckNAdd(138);
                  break;
               case 174:
                  if (curChar == 100)
                     jjCheckNAddTwoStates(175, 203);
                  break;
               case 175:
                  if (curChar != 111)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 176:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(407, 412);
                  break;
               case 177:
                  if (curChar == 95)
                     jjCheckNAdd(178);
                  break;
               case 179:
                  if (curChar == 95)
                     jjCheckNAddStates(413, 416);
                  break;
               case 180:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(178);
                  break;
               case 181:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(122, 124);
                  break;
               case 182:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 183:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(185, 175);
                  break;
               case 184:
                  if (curChar == 117)
                     jjCheckNAdd(125);
                  break;
               case 185:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 112)
                     jjAddStates(417, 418);
                  break;
               case 187:
                  if (curChar == 117)
                     jjCheckNAdd(138);
                  break;
               case 188:
                  if (curChar != 109)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 194:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 195:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar != 95)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 200:
                  if (curChar == 110)
                     jjCheckNAdd(125);
                  break;
               case 201:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 211:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(223, 250);
                  break;
               case 212:
                  if ((0x3800000128000000L & l) != 0L)
                     jjCheckNAddStates(223, 250);
                  break;
               case 215:
                  if (curChar == 110)
                     jjCheckNAddStates(223, 250);
                  break;
               case 216:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 114)
                     jjCheckNAddStates(223, 250);
                  break;
               case 223:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 108)
                     jjCheckNAddStates(223, 250);
                  break;
               case 227:
               case 283:
                  if (curChar == 97)
                     jjCheckNAdd(226);
                  break;
               case 228:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 101)
                     jjCheckNAddStates(223, 250);
                  break;
               case 231:
                  if (curChar == 115)
                     jjCheckNAdd(230);
                  break;
               case 232:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
               case 256:
                  if (curChar == 108)
                     jjCheckNAdd(230);
                  break;
               case 236:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 112)
                     jjCheckNAddStates(223, 250);
                  break;
               case 240:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 116)
                     jjCheckNAddStates(223, 250);
                  break;
               case 244:
               case 246:
                  if (curChar == 101)
                     jjCheckNAdd(243);
                  break;
               case 245:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 247:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 116)
                     jjCheckNAdd(230);
                  break;
               case 249:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 115)
                     jjCheckNAddStates(223, 250);
                  break;
               case 255:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 257:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 275:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(419, 424);
                  break;
               case 276:
                  if (curChar == 95)
                     jjCheckNAdd(277);
                  break;
               case 278:
                  if (curChar == 95)
                     jjCheckNAddStates(425, 428);
                  break;
               case 279:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(277);
                  break;
               case 280:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(311, 313);
                  break;
               case 281:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(223, 250);
                  break;
               case 282:
                  if (curChar == 110)
                     jjAddStates(429, 430);
                  break;
               case 284:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 111)
                     jjCheckNAdd(243);
                  break;
               case 289:
                  if (curChar == 100)
                     jjCheckNAddTwoStates(290, 310);
                  break;
               case 290:
                  if (curChar == 111)
                     jjCheckNAddStates(223, 250);
                  break;
               case 291:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(293, 290);
                  break;
               case 292:
                  if (curChar == 117)
                     jjCheckNAdd(230);
                  break;
               case 293:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 294:
                  if (curChar == 112)
                     jjAddStates(431, 432);
                  break;
               case 295:
                  if (curChar == 117)
                     jjCheckNAdd(243);
                  break;
               case 296:
                  if (curChar == 109)
                     jjCheckNAddStates(223, 250);
                  break;
               case 302:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 303:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 304:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 307:
                  if (curChar == 110)
                     jjCheckNAdd(230);
                  break;
               case 308:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if (curChar == 95)
                     jjCheckNAddStates(223, 250);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(433, 437);
                  break;
               case 66:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 67:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 68:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 69:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 189:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(438, 442);
                  break;
               case 190:
                  if (!jjCanMove_3(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 191:
                  if (!jjCanMove_4(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 192:
                  if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 193:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddStates(36, 63);
                  break;
               case 297:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(443, 447);
                  break;
               case 298:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(223, 250);
                  break;
               case 299:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(223, 250);
                  break;
               case 300:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(223, 250);
                  break;
               case 301:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(223, 250);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 329 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   320, 323, 327, 103, 210, 56, 70, 73, 104, 105, 107, 109, 116, 120, 124, 129, 
   133, 137, 140, 142, 148, 150, 157, 159, 160, 161, 162, 163, 164, 167, 174, 183, 
   186, 189, 176, 179, 104, 105, 107, 109, 116, 120, 124, 129, 133, 137, 140, 142, 
   148, 150, 157, 159, 160, 161, 162, 163, 164, 176, 179, 167, 174, 183, 186, 189, 
   165, 104, 105, 107, 109, 116, 120, 124, 129, 133, 137, 140, 142, 148, 150, 157, 
   159, 160, 161, 162, 163, 167, 174, 183, 186, 189, 176, 179, 205, 209, 104, 105, 
   107, 109, 116, 120, 124, 129, 133, 137, 140, 142, 148, 150, 157, 159, 160, 161, 
   162, 163, 167, 174, 183, 186, 189, 176, 179, 204, 104, 176, 179, 165, 104, 105, 
   107, 109, 116, 120, 124, 129, 133, 137, 140, 142, 148, 150, 157, 159, 160, 161, 
   162, 163, 164, 167, 174, 183, 186, 189, 176, 179, 205, 209, 206, 165, 207, 208, 
   206, 165, 207, 165, 104, 105, 107, 109, 116, 120, 124, 129, 133, 137, 140, 142, 
   148, 150, 157, 159, 160, 161, 162, 163, 164, 167, 174, 183, 186, 189, 176, 179, 
   205, 204, 209, 211, 212, 214, 221, 225, 229, 234, 238, 242, 245, 247, 253, 255, 
   262, 264, 265, 266, 267, 269, 270, 273, 282, 289, 291, 294, 297, 275, 278, 211, 
   212, 214, 221, 225, 229, 234, 238, 242, 245, 247, 253, 255, 262, 264, 265, 266, 
   267, 269, 270, 275, 278, 273, 282, 289, 291, 294, 297, 271, 211, 212, 214, 221, 
   225, 229, 234, 238, 242, 245, 247, 253, 255, 262, 264, 265, 266, 267, 269, 273, 
   282, 289, 291, 294, 297, 275, 278, 314, 318, 211, 212, 214, 221, 225, 229, 234, 
   238, 242, 245, 247, 253, 255, 262, 264, 265, 266, 267, 269, 273, 282, 289, 291, 
   294, 297, 275, 278, 313, 274, 312, 211, 275, 278, 271, 211, 212, 214, 221, 225, 
   229, 234, 238, 242, 245, 247, 253, 255, 262, 264, 265, 266, 267, 269, 270, 273, 
   282, 289, 291, 294, 297, 275, 278, 314, 318, 315, 271, 316, 317, 315, 271, 316, 
   271, 211, 212, 214, 221, 225, 229, 234, 238, 242, 245, 247, 253, 255, 262, 264, 
   265, 266, 267, 269, 270, 273, 282, 289, 291, 294, 297, 275, 278, 314, 313, 318, 
   324, 320, 325, 326, 324, 320, 325, 71, 72, 56, 77, 70, 73, 74, 72, 75, 
   76, 93, 98, 84, 85, 172, 173, 177, 178, 104, 199, 176, 179, 180, 178, 181, 
   182, 187, 198, 276, 277, 211, 311, 275, 278, 279, 277, 280, 281, 287, 288, 295, 
   306, 66, 67, 68, 69, 68, 190, 191, 190, 192, 193, 298, 299, 298, 300, 301, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec1[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec3[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_4(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec4[i2] & l2) != 0L);
      default : 
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x3fc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[329];
private final int[] jjstateSet = new int[658];
protected char curChar;
/** Constructor. */
public TokenizerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public TokenizerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 329; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
