/* Generated By:JavaCC: Do not edit this line. TokenizerConstants.java */
package br.univali.comp.parser.tokenizer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int SKIP_MARKERS = 3;
  /** RegularExpression Id. */
  int LINE = 4;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 9;
  /** RegularExpression Id. */
  int FLOAT_CONSTANT = 10;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 11;
  /** RegularExpression Id. */
  int ARITHMETIC = 12;
  /** RegularExpression Id. */
  int RESERVED_WORDS = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int LOGICAL = 15;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 16;
  /** RegularExpression Id. */
  int ERROR_INVALID_SYMBOL = 17;
  /** RegularExpression Id. */
  int ERROR_UNFINISHED_LITERAL_CONSTANT = 18;
  /** RegularExpression Id. */
  int ERROR_INTEGER_CONSTANT_FORMAT = 19;
  /** RegularExpression Id. */
  int ERROR_FLOAT_CONSTANT_FORMAT = 20;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<SKIP_MARKERS>",
    "<LINE>",
    "\":*\"",
    "<COMMENT_LINE>",
    "\"*:\"",
    "<token of kind 8>",
    "<INTEGER_CONSTANT>",
    "<FLOAT_CONSTANT>",
    "<LITERAL_CONSTANT>",
    "<ARITHMETIC>",
    "<RESERVED_WORDS>",
    "<IDENTIFIER>",
    "<LOGICAL>",
    "<SPECIAL_SYMBOL>",
    "<ERROR_INVALID_SYMBOL>",
    "<ERROR_UNFINISHED_LITERAL_CONSTANT>",
    "<ERROR_INTEGER_CONSTANT_FORMAT>",
    "<ERROR_FLOAT_CONSTANT_FORMAT>",
  };

}
