/* Generated By:JavaCC: Do not edit this line. TokenizerConstants.java */
package br.univali.comp.parser.tokenizer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int SKIP_MARKERS = 3;
  /** RegularExpression Id. */
  int LINE = 4;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int HEADER = 7;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 10;
  /** RegularExpression Id. */
  int FLOAT_CONSTANT = 11;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 12;
  /** RegularExpression Id. */
  int ARITHMETIC = 13;
  /** RegularExpression Id. */
  int RESERVED_WORDS = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int LOGICAL = 16;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 17;
  /** RegularExpression Id. */
  int ERROR_INVALID_SYMBOL = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<SKIP_MARKERS>",
    "<LINE>",
    "\":*\"",
    "<COMMENT_LINE>",
    "<HEADER>",
    "\"*:\"",
    "<token of kind 9>",
    "<INTEGER_CONSTANT>",
    "<FLOAT_CONSTANT>",
    "<LITERAL_CONSTANT>",
    "<ARITHMETIC>",
    "<RESERVED_WORDS>",
    "<IDENTIFIER>",
    "<LOGICAL>",
    "<SPECIAL_SYMBOL>",
    "<ERROR_INVALID_SYMBOL>",
  };

}
